### PR TITLE
chore(web): lint

### PR DESCRIPTION
**Pull request by sparrowhe**
I added [xo](https://github.com/xojs/xo) to the frontend project to check the code format.

And I have configured some rules. If there is anything wrong, please let me know.

### CODE REVIEW

**Review by wxiwnd — APPROVED** [review]
LGTM

**Comment by wxiwnd** [comment]
Thanks for your hard-work!
Could you include a guide in the README or CONTRIBUTING file when you have the time? Perhaps through another pull request. Your contribution would be greatly valued.

**Comment by wxiwnd** [comment]
to @ianzhaoyh please rebase your branch before commit, thank you.
cc @GEORGE-Ta

**Comment by ianzhaoyh** [comment]
LGTM

**Pull request merged**
